# Generated by Django 3.2.25 on 2024-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=64)),
                ('project_url', models.CharField(max_length=64)),
                ('project_author', models.CharField(max_length=64)),
                ('project_version', models.CharField(max_length=32)),
                ('project_cover', models.ImageField(null=True, upload_to='img/')),
                ('project_description', models.TextField()),
            ],
        ),
    ]
