# Generated by Django 3.2.25 on 2024-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpeclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
