# Generated by Django 3.2.25 on 2024-10-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpeclub', '0002_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_cover',
            field=models.CharField(default='static/imgs/logo.png', max_length=256),
        ),
    ]
